name: online_exam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.5
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get_it: 
  injectable: ^2.5.0 
  internet_connection_checker: ^3.0.1
  linear_progress_bar: ^1.1.3
  percent_indicator: ^4.2.4
  top_snackbar_flutter: ^3.2.0

  lottie: ^3.3.1
dev_dependencies:
  build_runner: 
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/slpash/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
#flutter_intl:
#  enabled: true