name: online_exam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  get_it: null
  injectable: null
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: null
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: null

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
