///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsInter18ptRegular = 'assets/fonts/Inter_18pt-Regular.ttf';
  static const String fontsRobotoRegular = 'assets/fonts/Roboto-Regular.ttf';
  static const String imagesAlram2 = 'assets/images/alram2.png';
  static const String imagesCamera = 'assets/images/Camera.svg';
  static const String imagesExam = 'assets/images/exam.png';
  static const String imagesProfilePhoto = 'assets/images/profile_photo.svg';
  static const String imagesSandClock1 = 'assets/images/sand-clock 1.png';
  static const String slpashSplashAnimation = 'assets/slpash/splash_animation.json';

}
